#
# Makefile for the sensor drivers.
#

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SENSORS_MAX86902)		+= max86902.o
obj-$(CONFIG_SENSORS_MAX_NOTCHFILTER)   += max_notchfilter/
obj-$(CONFIG_SENSORS_SSP_STM_RINATO)	+= stm_rinato/
