#
# Makefile for the phy drivers.
#

obj-$(CONFIG_GENERIC_PHY)		+= phy-core.o
obj-$(CONFIG_PHY_EXYNOS_MIPI_VIDEO)	+= phy-exynos-mipi-video.o
obj-$(CONFIG_PHY_EXYNOS_USB)		+= phy-exynos-usb.o
obj-$(CONFIG_PHY_EXYNOS4210_USB)	+= phy-exynos4210-usb.o
obj-$(CONFIG_PHY_EXYNOS4212_USB)	+= phy-exynos4212-usb.o
