#
# Makefile for the exynos video drivers.
#
obj-$(CONFIG_EXYNOS_LCD_S6E36W0X01)	+= s6e36w0x01.o s6e36w0x01_dimming.o
obj-$(CONFIG_EXYNOS_LCD_S6E36W1X01)	+= s6e36w1x01.o s6e36w1x01_dimming.o
obj-$(CONFIG_EXYNOS_LCD_S6E63J0X03)	+= s6e63j0x03.o s6e63j0x03_dimming.o
obj-$(CONFIG_EXYNOS_LCD_S6E8AX0)	+= s6e8ax0.o
obj-$(CONFIG_EXYNOS_DP)			+= exynos_dp_core.o exynos_dp_reg.o
obj-$(CONFIG_EXYNOS_MIPI_DSI)          += exynos_mipi_dsi.o exynos_mipi_dsi_common.o \
                                       exynos_mipi_dsi_lowlevel.o
obj-$(CONFIG_EXYNOS_SMIES)		  += exynos_smies.o
obj-$(CONFIG_LCD_S6E8AA0)      += s6e8aa0.o
obj-$(CONFIG_BACKLIGHT_SMART_DIMMING)  += smart_dimming.o
obj-$(CONFIG_LCD_L5F31188)      += l5f31188.o
obj-$(CONFIG_LCD_S6D6AA1)      += s6d6aa1.o
obj-$(CONFIG_LCD_S6D6FA0)      += s6d6fa0.o
obj-$(CONFIG_LCD_S6E8FA0)      += s6e8fa0.o smart_dimming_s6e8fa0.o
