ifeq ($(CONFIG_MALI_MIDGARD),y)
	obj-y += \
		mali_kbase_platform.o \
		gpu_notifier.o \
		gpu_control_exynos5422.o \
		gpu_control.o \
		gpu_dvfs_handler.o \
		gpu_dvfs_governor.o \
		gpu_custom_interface.o
	obj-$(CONFIG_CPU_THERMAL_IPA) += gpu_ipa.o
else ifeq ($(CONFIG_MALI_MIDGARD),m)
	SRC += \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/mali_kbase_platform.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_notifier.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_control_exynos5422.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_control.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_dvfs_handler.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_dvfs_governor.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_custom_interface.c
	ifeq ($(CONFIG_CPU_THERMAL_IPA),y)
		SRC += $(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_ipa.c
	endif
endif
