
#include <linux/i2c.h>
#include <linux/delay.h>
#include <linux/interrupt.h>
#include <linux/irq.h>
#include <mach/gpio.h>
#include <mach/hardware.h>
#include <media/v4l2-int-device.h>

#include <linux/firmware.h>
#include <linux/fs.h>
#include <linux/vmalloc.h>

#include "Camsensor_tunner_32bits_reg.h"
	
#if (CAM_S5K5CAG_DBG_MSG)
#include "dprintk.h"
#else
#define dprintk(x, y...)
#endif
	
static int debug = 7;
module_param(debug, int, 0644);

#define dprintk(level, fmt, arg...) do {	\
	if (debug >= level)			\
	printk("[5M-Tune]"fmt , ## arg); } while (0)
	
typedef struct tagCamReg32 {
	unsigned short addr;
	unsigned short value;
} CAM_REG32_T, *PCAM_REG32_T;

typedef struct tagCamReg32Package {
	CAM_REG32_T* reg32;
	int num;
	int nDynamicLoading; /* 0: static loading, 1: dynamic loading */
} CAM_REG32_PACKAGE_T, *PCAM_REG32_PACKAGE_T;

#define DEFAULT_REG_SET_AMOUNT 100

typedef enum
{
	CAMERA_CMD_TYPE_NONE,
	CAMERA_CMD_TYPE_READ,
	CAMERA_CMD_TYPE_WRITE
} Camera_Cmd_Parser_type;

#define CAMTUNING_INIT_ARM				"CAMTUNING_INIT_ARM"
#define CAMTUNING_INIT					"CAMTUNING_INIT"

#define CAMTUNING_EFFECT_OFF				"CAMTUNING_EFFECT_OFF"
#define CAMTUNING_EFFECT_MONO				"CAMTUNING_EFFECT_MONO"
#define CAMTUNING_EFFECT_SEPIA				"CAMTUNING_EFFECT_SEPIA"
#define CAMTUNING_EFFECT_NEGATIVE			"CAMTUNING_EFFECT_NEGATIVE"
#define CAMTUNING_EFFECT_AQUA				"CAMTUNING_EFFECT_AQUA"
#define CAMTUNING_EFFECT_SKETCH				"CAMTUNING_EFFECT_SKETCH"

#define CAMTUNING_WHITE_BALANCE_AUTO			"CAMTUNING_WHITE_BALANCE_AUTO"
#define CAMTUNING_WHITE_BALANCE_DAYLIGHT		"CAMTUNING_WHITE_BALANCE_DAYLIGHT"
#define CAMTUNING_WHITE_BALANCE_CLOUDY			"CAMTUNING_WHITE_BALANCE_CLOUDY"
#define CAMTUNING_WHITE_BALANCE_FLUORESCENT		"CAMTUNING_WHITE_BALANCE_FLUORESCENT"
#define CAMTUNING_WHITE_BALANCE_INCANDESCENT		"CAMTUNING_WHITE_BALANCE_INCANDESCENT"

#define CAMTUNING_WDR_ON				"CAMTUNING_WDR_ON"
#define CAMTUNING_WDR_OFF				"CAMTUNING_WDR_OFF"

#define CAMTUNING_CONTRAST_M_4				"CAMTUNING_CONTRAST_M_4"
#define CAMTUNING_CONTRAST_M_3				"CAMTUNING_CONTRAST_M_3"
#define CAMTUNING_CONTRAST_M_2				"CAMTUNING_CONTRAST_M_2"
#define CAMTUNING_CONTRAST_M_1				"CAMTUNING_CONTRAST_M_1"
#define CAMTUNING_CONTRAST_0				"CAMTUNING_CONTRAST_0"
#define CAMTUNING_CONTRAST_P_1				"CAMTUNING_CONTRAST_P_1"
#define CAMTUNING_CONTRAST_P_2				"CAMTUNING_CONTRAST_P_2"
#define CAMTUNING_CONTRAST_P_3				"CAMTUNING_CONTRAST_P_3"
#define CAMTUNING_CONTRAST_P_4				"CAMTUNING_CONTRAST_P_4"
#define CAMTUNING_SATURATION_M_2			"CAMTUNING_SATURATION_M_2"
#define CAMTUNING_SATURATION_M_1			"CAMTUNING_SATURATION_M_1"
#define CAMTUNING_SATURATION_0				"CAMTUNING_SATURATION_0"
#define CAMTUNING_SATURATION_P_1			"CAMTUNING_SATURATION_P_1"
#define CAMTUNING_SATURATION_P_2			"CAMTUNING_SATURATION_P_2"

#define CAMTUNING_SHARPNESS_M_3				"CAMTUNING_SHARPNESS_M_3"
#define CAMTUNING_SHARPNESS_M_2				"CAMTUNING_SHARPNESS_M_2"
#define CAMTUNING_SHARPNESS_M_1				"CAMTUNING_SHARPNESS_M_1"
#define CAMTUNING_SHARPNESS_0				"CAMTUNING_SHARPNESS_0"
#define CAMTUNING_SHARPNESS_P_1				"CAMTUNING_SHARPNESS_P_1"
#define CAMTUNING_SHARPNESS_P_2				"CAMTUNING_SHARPNESS_P_2"
#define CAMTUNING_SHARPNESS_P_3				"CAMTUNING_SHARPNESS_P_3"


#define CAMTUNING_BRIGHTNESS_M_4			"CAMTUNING_BRIGHTNESS_M_4"
#define CAMTUNING_BRIGHTNESS_M_3			"CAMTUNING_BRIGHTNESS_M_3"
#define CAMTUNING_BRIGHTNESS_M_2			"CAMTUNING_BRIGHTNESS_M_2"
#define CAMTUNING_BRIGHTNESS_M_1			"CAMTUNING_BRIGHTNESS_M_1"
#define CAMTUNING_BRIGHTNESS_0				"CAMTUNING_BRIGHTNESS_0"
#define CAMTUNING_BRIGHTNESS_P_1			"CAMTUNING_BRIGHTNESS_P_1"
#define CAMTUNING_BRIGHTNESS_P_2			"CAMTUNING_BRIGHTNESS_P_2"
#define CAMTUNING_BRIGHTNESS_P_3			"CAMTUNING_BRIGHTNESS_P_3"
#define CAMTUNING_BRIGHTNESS_P_4			"CAMTUNING_BRIGHTNESS_P_4"


#define CAMTUNING_SCENE_OFF				"CAMTUNING_SCENE_OFF"
#define CAMTUNING_SCENE_PORTRAIT			"CAMTUNING_SCENE_PORTRAIT"
#define CAMTUNING_SCENE_LANDSCAPE			"CAMTUNING_SCENE_LANDSCAPE"
#define CAMTUNING_SCENE_SPORTS				"CAMTUNING_SCENE_SPORTS"
#define CAMTUNING_SCENE_PARTY				"CAMTUNING_SCENE_PARTY"
#define CAMTUNING_SCENE_BEACH				"CAMTUNING_SCENE_BEACH"
#define CAMTUNING_SCENE_SUNSET				"CAMTUNING_SCENE_SUNSET"
#define CAMTUNING_SCENE_DAWN				"CAMTUNING_SCENE_DAWN"
#define CAMTUNING_SCENE_FALL				"CAMTUNING_SCENE_FALL"
#define CAMTUNING_SCENE_NIGHT				"CAMTUNING_SCENE_NIGHT"
#define CAMTUNING_SCENE_BACKLIGHT			"CAMTUNING_SCENE_BACKLIGHT"
#define CAMTUNING_SCENE_FIRE				"CAMTUNING_SCENE_FIRE"
#define CAMTUNING_SCENE_TEXT				"CAMTUNING_SCENE_TEXT"
#define CAMTUNING_SCENE_CANDLE				"CAMTUNING_SCENE_CANDLE"

#define CAMTUNING_METERING_MATRIX			"CAMTUNING_METERING_MATRIX"
#define CAMTUNING_METERING_SPOT				"CAMTUNING_METERING_SPOT"
#define CAMTUNING_METERING_CENTER			"CAMTUNING_METERING_CENTER"

#define CAMTUNING_ISO_AUTO				"CAMTUNING_ISO_AUTO"
#define CAMTUNING_ISO_50				"CAMTUNING_ISO_50"
#define CAMTUNING_ISO_100				"CAMTUNING_ISO_100"
#define CAMTUNING_ISO_200				"CAMTUNING_ISO_200"
#define CAMTUNING_ISO_400				"CAMTUNING_ISO_400"

#define CAMTUNING_RETURN_TO_PREVIEW			"CAMTUNING_RETURN_TO_PREVIEW"

#define CAMTUNING_HIGH_SNAPSHOT				"CAMTUNING_HIGH_SNAPSHOT"
#define CAMTUNING_NORMAL_SNAPSHOT			"CAMTUNING_NORMAL_SNAPSHOT"
#define CAMTUNING_LOWLIGHT_SNAPSHOT			"CAMTUNING_LOWLIGHT_SNAPSHOT"
#define CAMTUNING_NIGHT_SNAPSHOT			"CAMTUNING_NIGHT_SNAPSHOT"

#define CAMTUNING_30_FPS				"CAMTUNING_30_FPS"

#define CAMTUNING_AE_LOCK				"CAMTUNING_AE_LOCK"
#define CAMTUNING_AE_UNLOCK				"CAMTUNING_AE_UNLOCK"
#define CAMTUNING_AWB_LOCK				"CAMTUNING_AWB_LOCK"
#define CAMTUNING_AWB_UNLOCK				"CAMTUNING_AWB_UNLOCK"

#define CAMTUNING_DTP_ON				"CAMTUNING_DTP_ON"
#define CAMTUNING_DTP_OFF				"CAMTUNING_DTP_OFF"

#define CAMTUNING_CAMCORDER_SIZE_176_144		"CAMTUNING_CAMCORDER_SIZE_176_144"
#define CAMTUNING_CAMCORDER_SIZE_320_240		"CAMTUNING_CAMCORDER_SIZE_320_240"
#define CAMTUNING_CAMCORDER_SIZE_352_288		"CAMTUNING_CAMCORDER_SIZE_352_288"
#define CAMTUNING_CAMCORDER_SIZE_640_480		"CAMTUNING_CAMCORDER_SIZE_640_480"
#define CAMTUNING_CAMCORDER_SIZE_720_480		"CAMTUNING_CAMCORDER_SIZE_720_480"
#define CAMTUNING_CAMCORDER_SIZE_800_480		"CAMTUNING_CAMCORDER_SIZE_800_480"
#define CAMTUNING_CAMCORDER_SIZE_1280_720		"CAMTUNING_CAMCORDER_SIZE_1280_720"

#define CAMTUNING_PREVIEW_SIZE_144_176			"CAMTUNING_PREVIEW_SIZE_144_176"
#define CAMTUNING_PREVIEW_SIZE_176_144			"CAMTUNING_PREVIEW_SIZE_176_144"
#define CAMTUNING_PREVIEW_SIZE_320_240			"CAMTUNING_PREVIEW_SIZE_320_240"
#define CAMTUNING_PREVIEW_SIZE_352_288			"CAMTUNING_PREVIEW_SIZE_352_288"
#define CAMTUNING_PREVIEW_SIZE_640_480			"CAMTUNING_PREVIEW_SIZE_640_480"
#define CAMTUNING_PREVIEW_SIZE_720_480			"CAMTUNING_PREVIEW_SIZE_720_480"
#define CAMTUNING_PREVIEW_SIZE_800_480			"CAMTUNING_PREVIEW_SIZE_800_480"

#define CAMTUNING_CAPTURE_SIZE_160_120			"CAMTUNING_CAPTURE_SIZE_160_120"
#define CAMTUNING_CAPTURE_SIZE_320_240			"CAMTUNING_CAPTURE_SIZE_320_240"
#define CAMTUNING_CAPTURE_SIZE_640_480			"CAMTUNING_CAPTURE_SIZE_640_480"
#define CAMTUNING_CAPTURE_SIZE_800_480			"CAMTUNING_CAPTURE_SIZE_800_480"
#define CAMTUNING_CAPTURE_SIZE_1024_768			"CAMTUNING_CAPTURE_SIZE_1024_768"
#define CAMTUNING_CAPTURE_SIZE_1280_960			"CAMTUNING_CAPTURE_SIZE_1280_960"
#define CAMTUNING_CAPTURE_SIZE_1600_960			"CAMTUNING_CAPTURE_SIZE_1600_960"
#define CAMTUNING_CAPTURE_SIZE_1600_1200		"CAMTUNING_CAPTURE_SIZE_1600_1200"
#define CAMTUNING_CAPTURE_SIZE_2048_1232		"CAMTUNING_CAPTURE_SIZE_2048_1232"
#define CAMTUNING_CAPTURE_SIZE_2048_1536		"CAMTUNING_CAPTURE_SIZE_2048_1536"
#define CAMTUNING_CAPTURE_SIZE_2560_1536		"CAMTUNING_CAPTURE_SIZE_2560_1536"
#define CAMTUNING_CAPTURE_SIZE_2560_1920		"CAMTUNING_CAPTURE_SIZE_2560_1920"

#define CAMTUNING_CAPTURE_SIZE_176_144			"CAMTUNING_CAPTURE_SIZE_176_144"
#define CAMTUNING_CAPTURE_SIZE_352_288			"CAMTUNING_CAPTURE_SIZE_352_288"

#define CAMTUNING_JPEG_QUALITY_SUPERFINE		"CAMTUNING_JPEG_QUALITY_SUPERFINE"
#define CAMTUNING_JPEG_QUALITY_FINE			"CAMTUNING_JPEG_QUALITY_FINE"
#define CAMTUNING_JPEG_QUALITY_NORMAL			"CAMTUNING_JPEG_QUALITY_NORMAL"

#define CAMTUNING_FLASH_INIT 				"CAMTUNING_FLASH_INIT"
#define CAMTUNING_LOW_CAP_ON 				"CAMTUNING_LOW_CAP_ON"
#define CAMTUNING_LOW_CAP_OFF 				"CAMTUNING_LOW_CAP_OFF"

#define CAMTUNING_NIGHT_CAP_ON 				"CAMTUNING_NIGHT_CAP_ON"
#define CAMTUNING_NIGHT_CAP_OFF 			"CAMTUNING_NIGHT_CAP_OFF"

#define CAMTUNING_AF_START				"CAMTUNING_AF_START"
#define CAMTUNING_AF_NORMAL_MODE_1			"CAMTUNING_AF_NORMAL_MODE_1"
#define CAMTUNING_AF_NORMAL_MODE_2			"CAMTUNING_AF_NORMAL_MODE_2"
#define CAMTUNING_AF_NORMAL_MODE_3			"CAMTUNING_AF_NORMAL_MODE_3"
#define CAMTUNING_AF_NORMAL_MODE_4			"CAMTUNING_AF_NORMAL_MODE_4"

#define CAMTUNING_AF_MACRO_MODE_1			"CAMTUNING_AF_MACRO_MODE_1"
#define CAMTUNING_AF_MACRO_MODE_2			"CAMTUNING_AF_MACRO_MODE_2"
#define CAMTUNING_AF_MACRO_MODE_3			"CAMTUNING_AF_MACRO_MODE_3"

#define CAMTUNING_AF_OFF_1				"CAMTUNING_AF_OFF_1"
#define CAMTUNING_AF_OFF_2				"CAMTUNING_AF_OFF_2"
#define CAMTUNING_AF_OFF_3				"CAMTUNING_AF_OFF_3"

#define CAMTUNING_AF_NORMAL_ON				"CAMTUNING_AF_NORMAL_ON"
#define CAMTUNING_AF_MACRO_ON				"CAMTUNING_AF_MACRO_ON"
#define CAMTUNING_AF_FOCUS_DO				"CAMTUNING_AF_FOCUS_DO"
#define CAMTUNING_AF_OFF				"CAMTUNING_AF_OFF"

#define CAMTUNING_X1_25_ZOOM_0				"CAMTUNING_X1_25_ZOOM_0"
#define CAMTUNING_X1_25_ZOOM_1				"CAMTUNING_X1_25_ZOOM_1"
#define CAMTUNING_X1_25_ZOOM_2				"CAMTUNING_X1_25_ZOOM_2"
#define CAMTUNING_X1_25_ZOOM_3				"CAMTUNING_X1_25_ZOOM_3"
#define CAMTUNING_X1_25_ZOOM_4				"CAMTUNING_X1_25_ZOOM_4"
#define CAMTUNING_X1_25_ZOOM_5				"CAMTUNING_X1_25_ZOOM_5"
#define CAMTUNING_X1_25_ZOOM_6				"CAMTUNING_X1_25_ZOOM_6"
#define CAMTUNING_X1_25_ZOOM_7				"CAMTUNING_X1_25_ZOOM_7"
#define CAMTUNING_X1_25_ZOOM_8				"CAMTUNING_X1_25_ZOOM_8"

#define CAMTUNING_X1_6_ZOOM_0				"CAMTUNING_X1_6_ZOOM_0"
#define CAMTUNING_X1_6_ZOOM_1				"CAMTUNING_X1_6_ZOOM_1"
#define CAMTUNING_X1_6_ZOOM_2				"CAMTUNING_X1_6_ZOOM_2"
#define CAMTUNING_X1_6_ZOOM_3				"CAMTUNING_X1_6_ZOOM_3"
#define CAMTUNING_X1_6_ZOOM_4				"CAMTUNING_X1_6_ZOOM_4"
#define CAMTUNING_X1_6_ZOOM_5				"CAMTUNING_X1_6_ZOOM_5"
#define CAMTUNING_X1_6_ZOOM_6				"CAMTUNING_X1_6_ZOOM_6"
#define CAMTUNING_X1_6_ZOOM_7				"CAMTUNING_X1_6_ZOOM_7"
#define CAMTUNING_X1_6_ZOOM_8				"CAMTUNING_X1_6_ZOOM_8"

#define CAMTUNING_X1_77_ZOOM_0				"CAMTUNING_X1_77_ZOOM_0"
#define CAMTUNING_X1_77_ZOOM_1				"CAMTUNING_X1_77_ZOOM_1"
#define CAMTUNING_X1_77_ZOOM_2				"CAMTUNING_X1_77_ZOOM_2"
#define CAMTUNING_X1_77_ZOOM_3				"CAMTUNING_X1_77_ZOOM_3"
#define CAMTUNING_X1_77_ZOOM_4				"CAMTUNING_X1_77_ZOOM_4"
#define CAMTUNING_X1_77_ZOOM_5				"CAMTUNING_X1_77_ZOOM_5"
#define CAMTUNING_X1_77_ZOOM_6				"CAMTUNING_X1_77_ZOOM_6"
#define CAMTUNING_X1_77_ZOOM_7				"CAMTUNING_X1_77_ZOOM_7"
#define CAMTUNING_X1_77_ZOOM_8				"CAMTUNING_X1_77_ZOOM_8"

#define CAMTUNING_X2_ZOOM_0				"CAMTUNING_X2_ZOOM_0"
#define CAMTUNING_X2_ZOOM_1				"CAMTUNING_X2_ZOOM_1"
#define CAMTUNING_X2_ZOOM_2				"CAMTUNING_X2_ZOOM_2"
#define CAMTUNING_X2_ZOOM_3				"CAMTUNING_X2_ZOOM_3"
#define CAMTUNING_X2_ZOOM_4				"CAMTUNING_X2_ZOOM_4"
#define CAMTUNING_X2_ZOOM_5				"CAMTUNING_X2_ZOOM_5"
#define CAMTUNING_X2_ZOOM_6				"CAMTUNING_X2_ZOOM_6"
#define CAMTUNING_X2_ZOOM_7				"CAMTUNING_X2_ZOOM_7"
#define CAMTUNING_X2_ZOOM_8				"CAMTUNING_X2_ZOOM_8"

extern CAM_REG32_PACKAGE_T CAM_REG32SET_INIT_ARM;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_INIT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_EFFECT_OFF;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_EFFECT_MONO;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_EFFECT_SEPIA;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_EFFECT_NEGATIVE;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_EFFECT_AQUA;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_EFFECT_SKETCH;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_WHITE_BALANCE_AUTO;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_WHITE_BALANCE_DAYLIGHT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_WHITE_BALANCE_CLOUDY;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_WHITE_BALANCE_FLUORESCENT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_WHITE_BALANCE_INCANDESCENT;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_WDR_ON;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_WDR_OFF;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_CONTRAST_M_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CONTRAST_M_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CONTRAST_0;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CONTRAST_P_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CONTRAST_P_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SATURATION_M_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SATURATION_M_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SATURATION_0;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SATURATION_P_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SATURATION_P_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SHARPNESS_M_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SHARPNESS_M_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SHARPNESS_0;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SHARPNESS_P_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SHARPNESS_P_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_M_4;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_M_3;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_M_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_M_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_0;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_P_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_P_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_P_3;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_BRIGHTNESS_P_4;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_OFF;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_OFF_NONE;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_OFF_SPORTS;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_OFF_NIGHT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_PORTRAIT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_LANDSCAPE;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_SPORTS;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_PARTY;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_BEACH;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_SUNSET;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_DAWN;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_FALL;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_NIGHT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_BACKLIGHT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_FIRE;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_TEXT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_SCENE_CANDLE;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_METERING_MATRIX;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_METERING_SPOT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_METERING_CENTER;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_ISO_AUTO;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_ISO_50;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_ISO_100;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_ISO_200;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_ISO_400;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_RETURN_TO_PREVIEW;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_HIGH_SNAPSHOT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_NORMAL_SNAPSHOT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_LOWLIGHT_SNAPSHOT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_NIGHT_SNAPSHOT;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_5_FPS;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_7_FPS;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_10_FPS;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_15_FPS;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_30_FPS;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_AUTO15_FPS;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_AUTO30_FPS;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AE_LOCK;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AE_UNLOCK;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AWB_LOCK;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AWB_UNLOCK;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_DO;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_NORMAL_ON;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_MACRO_ON;
//extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_OFF;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_DTP_ON;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_DTP_OFF;


extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAMCORDER_SIZE_176_144;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAMCORDER_SIZE_320_240;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAMCORDER_SIZE_352_288;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAMCORDER_SIZE_640_480;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAMCORDER_SIZE_720_480;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAMCORDER_SIZE_800_480;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAMCORDER_SIZE_1280_720;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_PREVIEW_SIZE_144_176;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_PREVIEW_SIZE_176_144;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_PREVIEW_SIZE_320_240;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_PREVIEW_SIZE_352_288;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_PREVIEW_SIZE_640_480;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_PREVIEW_SIZE_720_480;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_PREVIEW_SIZE_800_480;

// 4:3(Normal)
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_640_480;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_800_480;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_1280_960;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_1600_960;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_1600_1200;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_2048_1232;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_2048_1536;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_2560_1536;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_2560_1920;

// CIF & QCIF
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_176_144;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_CAPTURE_SIZE_352_288;


extern CAM_REG32_PACKAGE_T CAM_REG32SET_JPEG_QUALITY_SUPERFINE;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_JPEG_QUALITY_FINE;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_JPEG_QUALITY_NORMAL;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_FLASH_INIT;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_LOW_CAP_ON;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_LOW_CAP_OFF;
	
extern CAM_REG32_PACKAGE_T CAM_REG32SET_NIGHT_CAP_ON;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_NIGHT_CAP_OFF;
	
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_START;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_NORMAL_MODE_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_NORMAL_MODE_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_NORMAL_MODE_3;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_NORMAL_MODE_4;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_MACRO_MODE_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_MACRO_MODE_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_MACRO_MODE_3;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_OFF_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_OFF_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_AF_OFF_3;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_0;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_3;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_4;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_5;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_6;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_7;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_25_ZOOM_8;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_0;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_3;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_4;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_5;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_6;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_7;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_6_ZOOM_8;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_0;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_3;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_4;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_5;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_6;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_7;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X1_77_ZOOM_8;

extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_0;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_1;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_2;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_3;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_4;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_5;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_6;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_7;
extern CAM_REG32_PACKAGE_T CAM_REG32SET_X2_ZOOM_8;
	
unsigned int StringToHexFor32Bit( char *ss )
{
	int len = strlen( ss );
	int i = 0 ;
	unsigned int val = 0;   

	//To delete 0x or 0X characters
	if( !strncmp(L"0x", ss, 2) ||!strncmp(L"0X", ss, 2)) 
		ss[1] = '0';

	for ( i = 0 ; i < len ; i++ )
	{    
		if( ss[i] >='0' && ss[i] <='9' )
			val = val*16 + ( ss[i] - '0' );
		else if(ss[i] >='a' && ss[i] <='f' ) 
			val = val*16 + ( ss[i] - 'a'+10 );
		else if(ss[i] >='A' && ss[i] <='F' ) 
			val = val*16 + ( ss[i] - 'A'+10 );
		else
			break;
	}

	return val;
}

void CreateReg32Buffer(PCAM_REG32_PACKAGE_T pRegPackage, CAM_REG32_T* pRegBuf, int iDataAmount)
{
	int i=0;
		CAM_REG32_T* pRegTemp = NULL;

	//pRegTemp = (CAM_REG32_T*) malloc( iDataAmount * sizeof(CAM_REG32_T) );
	pRegTemp = (CAM_REG32_T*)kmalloc(iDataAmount * sizeof(CAM_REG32_T), GFP_KERNEL);

		if ( NULL == pRegTemp )
		{
			printk("[CAMSENSOR_TUNNER_REG32] CreateRegBuffer() - malloc() failed!!! \n" );
		return -ENOMEM;
		}
	memcpy( pRegTemp, pRegBuf, iDataAmount * sizeof(CAM_REG32_T) );

	pRegPackage->reg32= pRegTemp;
	pRegPackage->num= iDataAmount;
	pRegPackage->nDynamicLoading = 1;
		
		
#if 0 //for Debug
		for(i=0; i<iDataAmount; i++)
		{
			dprintk(6, "{0x%x, 0x%x} \n", pRegPackage->reg32[i].addr, pRegPackage->reg32[i].value);
		}
#endif //End Hoya
	printk("############### CreateReg32Buffer : iDataAmount = %d ###############\n", iDataAmount);
		
}

void DeleteReg32Buffer(PCAM_REG32_PACKAGE_T pRegPackage)
{
	if ( pRegPackage->nDynamicLoading == 1)
	{
		if ( pRegPackage->reg32 != NULL )
		{
			kfree(pRegPackage->reg32);
		}
	}

	pRegPackage->reg32 = NULL;
	pRegPackage->num = 0;
	pRegPackage->nDynamicLoading = 0;
}

void Copy2Reg32Buffer(char* pszStr, CAM_REG32_T* pRegBuf, int iDataAmount)
{
	if( 0 == iDataAmount ) return;
	dprintk(5, "Copy2Reg32Buffer :  %s \n", pszStr);

	if ( !strcmp( pszStr, CAMTUNING_INIT_ARM) ) {
		CreateReg32Buffer(&CAM_REG32SET_INIT_ARM, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_INIT) ) {
		CreateReg32Buffer(&CAM_REG32SET_INIT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_RETURN_TO_PREVIEW) ) {
		CreateReg32Buffer(&CAM_REG32SET_RETURN_TO_PREVIEW, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_30_FPS) ) {
		CreateReg32Buffer(&CAM_REG32SET_30_FPS, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_NORMAL_SNAPSHOT) ) {
		CreateReg32Buffer(&CAM_REG32SET_NORMAL_SNAPSHOT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_LOWLIGHT_SNAPSHOT) ) {
		CreateReg32Buffer(&CAM_REG32SET_LOWLIGHT_SNAPSHOT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_NIGHT_SNAPSHOT) ) {
		CreateReg32Buffer(&CAM_REG32SET_NIGHT_SNAPSHOT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_M_4) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_M_4, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_M_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_M_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_M_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_M_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_M_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_M_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_0) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_0, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_P_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_P_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_P_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_P_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_P_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_P_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_BRIGHTNESS_P_4) ) {
		CreateReg32Buffer(&CAM_REG32SET_BRIGHTNESS_P_4, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CONTRAST_M_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_CONTRAST_M_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CONTRAST_M_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_CONTRAST_M_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CONTRAST_0) ) {
		CreateReg32Buffer(&CAM_REG32SET_CONTRAST_0, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CONTRAST_P_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_CONTRAST_P_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CONTRAST_P_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_CONTRAST_P_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SATURATION_M_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_SATURATION_M_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SATURATION_M_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_SATURATION_M_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SATURATION_0) ) {
		CreateReg32Buffer(&CAM_REG32SET_SATURATION_0, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SATURATION_P_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_SATURATION_P_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SATURATION_P_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_SATURATION_P_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SHARPNESS_M_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_SHARPNESS_M_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SHARPNESS_M_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_SHARPNESS_M_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SHARPNESS_0) ) {
		CreateReg32Buffer(&CAM_REG32SET_SHARPNESS_0, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SHARPNESS_P_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_SHARPNESS_P_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SHARPNESS_P_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_SHARPNESS_P_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_WHITE_BALANCE_AUTO) ) {
		CreateReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_AUTO, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_WHITE_BALANCE_DAYLIGHT) ) {
		CreateReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_DAYLIGHT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_WHITE_BALANCE_CLOUDY) ) {
		CreateReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_CLOUDY, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_WHITE_BALANCE_FLUORESCENT) ) {
		CreateReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_FLUORESCENT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_WHITE_BALANCE_INCANDESCENT) ) {
		CreateReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_INCANDESCENT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_WDR_ON) ) {
		CreateReg32Buffer(&CAM_REG32SET_WDR_ON, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_WDR_OFF) ) {
		CreateReg32Buffer(&CAM_REG32SET_WDR_OFF, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_EFFECT_OFF) ) {
		CreateReg32Buffer(&CAM_REG32SET_EFFECT_OFF, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_EFFECT_MONO) ) {
		CreateReg32Buffer(&CAM_REG32SET_EFFECT_MONO, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_EFFECT_SEPIA) ) {
		CreateReg32Buffer(&CAM_REG32SET_EFFECT_SEPIA, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_EFFECT_AQUA) ) {
		CreateReg32Buffer(&CAM_REG32SET_EFFECT_AQUA, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_EFFECT_NEGATIVE) ) {
		CreateReg32Buffer(&CAM_REG32SET_EFFECT_NEGATIVE, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_OFF) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_OFF, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_PORTRAIT) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_PORTRAIT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_LANDSCAPE) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_LANDSCAPE, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_SPORTS) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_SPORTS, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_PARTY) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_PARTY, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_BEACH) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_BEACH, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_SUNSET) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_SUNSET, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_DAWN) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_DAWN, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_FALL) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_FALL, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_NIGHT) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_NIGHT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_BACKLIGHT) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_BACKLIGHT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_FIRE) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_FIRE, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_TEXT) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_TEXT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_SCENE_CANDLE) ) {
		CreateReg32Buffer(&CAM_REG32SET_SCENE_CANDLE, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_ISO_AUTO) ) {
		CreateReg32Buffer(&CAM_REG32SET_ISO_AUTO, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_ISO_50) ) {
		CreateReg32Buffer(&CAM_REG32SET_ISO_50, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_ISO_100) ) {
		CreateReg32Buffer(&CAM_REG32SET_ISO_100, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_ISO_200) ) {
		CreateReg32Buffer(&CAM_REG32SET_ISO_200, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_ISO_400) ) { 
		CreateReg32Buffer(&CAM_REG32SET_ISO_400, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_METERING_MATRIX) ) { 
		CreateReg32Buffer(&CAM_REG32SET_METERING_MATRIX, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_METERING_SPOT) ) {
		CreateReg32Buffer(&CAM_REG32SET_METERING_SPOT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_METERING_CENTER) ) {
		CreateReg32Buffer(&CAM_REG32SET_METERING_CENTER, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAMCORDER_SIZE_176_144) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_176_144, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAMCORDER_SIZE_320_240) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_320_240, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAMCORDER_SIZE_352_288) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_352_288, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAMCORDER_SIZE_640_480) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_640_480, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAMCORDER_SIZE_720_480) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_720_480, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAMCORDER_SIZE_800_480) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_800_480, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAMCORDER_SIZE_1280_720) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_1280_720, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_PREVIEW_SIZE_144_176 ) ) {
		CreateReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_144_176, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_PREVIEW_SIZE_176_144 ) ) {
		CreateReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_176_144, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_PREVIEW_SIZE_320_240 ) ) {
		CreateReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_320_240, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_PREVIEW_SIZE_640_480 ) ) {
		CreateReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_640_480, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_PREVIEW_SIZE_720_480 ) ) {
		CreateReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_720_480, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_PREVIEW_SIZE_800_480) ) {
		CreateReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_800_480, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_640_480) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_640_480, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_800_480) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_800_480, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_1280_960) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_1280_960, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_1600_960) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_1600_960, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_1600_1200) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_1600_1200, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_2048_1232) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_2048_1232, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_2048_1536) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_2048_1536, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_2560_1536) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_2560_1536, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_CAPTURE_SIZE_2560_1920) ) {
		CreateReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_2560_1920, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_JPEG_QUALITY_SUPERFINE) ) {
		CreateReg32Buffer(&CAM_REG32SET_JPEG_QUALITY_SUPERFINE, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_JPEG_QUALITY_FINE) ) {
		CreateReg32Buffer(&CAM_REG32SET_JPEG_QUALITY_FINE, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_JPEG_QUALITY_NORMAL) ) {
		CreateReg32Buffer(&CAM_REG32SET_JPEG_QUALITY_NORMAL, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_FLASH_INIT) ) {
		CreateReg32Buffer(&CAM_REG32SET_FLASH_INIT, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_LOW_CAP_ON) ) {
		CreateReg32Buffer(&CAM_REG32SET_LOW_CAP_ON, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_LOW_CAP_OFF) ) {
		CreateReg32Buffer(&CAM_REG32SET_LOW_CAP_OFF, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_NIGHT_CAP_ON) ) {
		CreateReg32Buffer(&CAM_REG32SET_NIGHT_CAP_ON, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_NIGHT_CAP_OFF) ) {
		CreateReg32Buffer(&CAM_REG32SET_NIGHT_CAP_OFF, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_START) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_START, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_NORMAL_MODE_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_NORMAL_MODE_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_NORMAL_MODE_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_NORMAL_MODE_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_NORMAL_MODE_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_NORMAL_MODE_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_NORMAL_MODE_4) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_NORMAL_MODE_4, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_MACRO_MODE_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_MACRO_MODE_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_MACRO_MODE_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_MACRO_MODE_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_MACRO_MODE_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_MACRO_MODE_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_OFF_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_OFF_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_OFF_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_OFF_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_AF_OFF_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_AF_OFF_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_0) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_0, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_4) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_4, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_5) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_5, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_6) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_6, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_7) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_7, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_25_ZOOM_8) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_8, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_0) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_0, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_4) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_4, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_5) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_5, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_6) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_6, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_7) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_7, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_6_ZOOM_8) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_8, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_0) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_0, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_4) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_4, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_5) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_5, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_6) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_6, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_7) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_7, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X1_77_ZOOM_8) ) {
		CreateReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_8, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_0) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_0, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_1) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_1, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_2) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_2, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_3) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_3, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_4) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_4, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_5) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_5, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_6) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_6, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_7) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_7, pRegBuf, iDataAmount);
	} else if ( !strcmp( pszStr, CAMTUNING_X2_ZOOM_8) ) {
		CreateReg32Buffer(&CAM_REG32SET_X2_ZOOM_8, pRegBuf, iDataAmount);
	}

	/*
	   else if ( !strcmp( pszStr, CAMTUNING_AF_NORMAL_ON) )
	   {
	   CreateReg32Buffer(&CAM_REG32SET_AF_NORMAL_ON, pRegBuf, iDataAmount);
	   }
	   else if ( !strcmp( pszStr, CAMTUNING_AF_MACRO_ON) )
	   {
	   CreateReg32Buffer(&CAM_REG32SET_AF_MACRO_ON, pRegBuf, iDataAmount);
	   }
	   else if ( !strcmp( pszStr, CAMTUNING_AF_FOCUS_DO) )
	   {
	   CreateReg32Buffer(&CAM_REG32SET_AF_DO, pRegBuf, iDataAmount);
	   }
	   else if ( !strcmp( pszStr, CAMTUNING_AF_OFF) )
	   {
	   CreateReg32Buffer(&CAM_REG32SET_AF_OFF, pRegBuf, iDataAmount);
	   }
	   */

}

#define NONE_MODE		0
#define READ_MODE		1
#define WRITE_MODE		2

#define REG_SET_COUNT		100
#define MAX_PATH		256
#define CAMIF_CONFIGURE_FILE	"/sdcard/CamTuning_32Bit.txt"

void Load32BitTuningFile()
{
	char* buffer = NULL;
	int buf_index = 0;
	unsigned int file_size = 0;

	struct file *filep = NULL;
	mm_segment_t oldfs;

	char wch;
	char szRegAddr[MAX_PATH];
	char szRegValue[MAX_PATH];
	char szCommand[MAX_PATH];

	unsigned int dwRegAddr = 0;
	unsigned int dwRegValue = 0;

	char strTuningCommand[MAX_PATH];
	char strTuningOutLog[MAX_PATH];

	int nMode = 0;
	int nStartTurning = 0;
	int nStartAddr = 0;
	int nStartValue = 0;
	int nStartHex = 0;
	int nStartCommand = 0;
	int nStartParsing = 0;

	CAM_REG32_T* pRegBuf = NULL;
	CAM_REG32_T* ptmpBuf = NULL;
	int nRegSetCount = 0;
	int nRegSetMaxCount = 0;

	filep = filp_open(CAMIF_CONFIGURE_FILE, O_RDONLY, 0);

	if (filep && (filep!= 0xfffffffe) && (filep!=0xfffffff3)) {
		oldfs = get_fs();
		set_fs(KERNEL_DS);
		file_size = filep->f_op->llseek(filep, 0, SEEK_END);
		filep->f_op->llseek(filep, 0, SEEK_SET);
		buffer = (char*)kmalloc(file_size+1, GFP_KERNEL);
		filep->f_op->read(filep, buffer, file_size, &filep->f_pos);
		buffer[file_size] = '\0';
		filp_close(filep, current->files);
		set_fs(oldfs);

		printk("Load32BitTuningFile : File Size = %d \n", file_size);
	} else {
		printk("Load32BitTuningFile : Do not find %s file !! \n", CAMIF_CONFIGURE_FILE);
		return;
	}

	while((file_size - buf_index)> 0) {
		//wch = fgetwc(fTurning);
		wch = buffer[buf_index];
		buf_index = buf_index+1;

		//Command
		if( !strncmp(L"[", &wch, 1) ) {
			if(  nStartParsing ) {
				Copy2Reg32Buffer( szCommand, pRegBuf, nRegSetCount );

				//free( pRegBuf );
				kfree( pRegBuf );
				pRegBuf = NULL;
			}
			nStartParsing = 0;
			nStartCommand = 1;
			memset( szCommand, 0x00, MAX_PATH);
			continue;
		}

		if( !strncmp(L"]", &wch, 1) ) {
			//pRegBuf = (CAM_REG32_T*) malloc( REG_SET_COUNT * sizeof(CAM_REG32_T) );
			pRegBuf = (CAM_REG32_T*)kmalloc(REG_SET_COUNT * sizeof(CAM_REG32_T), GFP_KERNEL);

			nStartParsing = 1;
			nStartCommand = 0;

			nRegSetCount = 0;
			nRegSetMaxCount = REG_SET_COUNT;
			continue;
		}

		if( nStartCommand ) strncat(szCommand, &wch, 1);

		//Address and Value
		if( nStartParsing ) {
			if( !strncmp(L"{", &wch, 1) ) {
				nStartTurning	= 1;
				nMode		= WRITE_MODE;
				nStartAddr	= 1;
				nStartValue	= 0;
				nStartHex	= 0;

				memset(szRegAddr, 0x00, sizeof(char)*MAX_PATH);
				memset(szRegValue, 0x00, sizeof(char)*MAX_PATH);

				dwRegAddr = 0x00;
				dwRegValue = 0x00;
				continue;
			}

			if( !strncmp(L"}", &wch, 1) ) {
				dwRegAddr = StringToHexFor32Bit(szRegAddr);
				dwRegValue = StringToHexFor32Bit(szRegValue); 

				if(nMode == WRITE_MODE) {		
					if( nRegSetCount >= nRegSetMaxCount  ) {
						int inc_num = nRegSetMaxCount /REG_SET_COUNT;
						inc_num++;
						//ptmpBuf = (CAM_REG32_T*) malloc( REG_SET_COUNT * inc_num * sizeof(CAM_REG32_T) );
						ptmpBuf = (CAM_REG32_T*)kmalloc(REG_SET_COUNT * inc_num * sizeof(CAM_REG32_T), GFP_KERNEL);
						memset( ptmpBuf, 0x00, REG_SET_COUNT * inc_num * sizeof(CAM_REG32_T) );

						inc_num--;
						memcpy( ptmpBuf, pRegBuf, REG_SET_COUNT * inc_num * sizeof(CAM_REG32_T) );

						//free( pRegBuf );
						kfree( pRegBuf );

						inc_num++;
						//pRegBuf = (CAM_REG32_T*) malloc( REG_SET_COUNT * inc_num * sizeof(CAM_REG32_T) );
						pRegBuf = (CAM_REG32_T*)kmalloc(REG_SET_COUNT * inc_num * sizeof(CAM_REG32_T), GFP_KERNEL);
						memset( pRegBuf, 0x00, REG_SET_COUNT * inc_num * sizeof(CAM_REG32_T) );

						inc_num--;
						memcpy( pRegBuf, ptmpBuf, REG_SET_COUNT * inc_num * sizeof(CAM_REG32_T) );

						inc_num++;
						nRegSetMaxCount = REG_SET_COUNT * inc_num;
					}

					pRegBuf[nRegSetCount].addr	= dwRegAddr;
					pRegBuf[nRegSetCount].value	= dwRegValue;
					nRegSetCount++;
				}

				nStartTurning = 0;
				continue;
			}

			if (!strncmp(L",", &wch, 1))
			{
				nStartAddr	= 0;
				nStartValue	= 1;
				nStartHex	= 0;
				continue;
			}

			if (!nStartHex && !strncmp(L"0", &wch, 1) ) continue;

			if (!strncmp(L"x", &wch, 1) ) {
				nStartHex   = 1;
				continue;
			}

			if (!strncmp(L"X", &wch, 1)) {
				nStartHex   = 1;
				continue;
			}

			if (!strncmp(L" ", &wch, 1))
				continue;

			if (nStartTurning)
			{
				if(nStartAddr)
					strncat(szRegAddr, &wch, 1);

				if(nStartValue)
					strncat(szRegValue, &wch, 1);
			}
		}

	}

	if (nStartParsing) {
		Copy2Reg32Buffer(szCommand, pRegBuf, nRegSetCount);

		//free( pRegBuf );
		kfree(pRegBuf);
		pRegBuf = NULL;
	}

	kfree(buffer);
	buffer = NULL;

	return;
}

void UnLoad32BitTuningFile()
{
	DeleteReg32Buffer(&CAM_REG32SET_INIT_ARM);
	DeleteReg32Buffer(&CAM_REG32SET_INIT);
	DeleteReg32Buffer(&CAM_REG32SET_EFFECT_OFF);
	DeleteReg32Buffer(&CAM_REG32SET_EFFECT_MONO);
	DeleteReg32Buffer(&CAM_REG32SET_EFFECT_SEPIA);
	DeleteReg32Buffer(&CAM_REG32SET_EFFECT_NEGATIVE);
	DeleteReg32Buffer(&CAM_REG32SET_EFFECT_AQUA);
	DeleteReg32Buffer(&CAM_REG32SET_EFFECT_SKETCH);
	DeleteReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_AUTO);
	DeleteReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_DAYLIGHT);
	DeleteReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_CLOUDY);
	DeleteReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_FLUORESCENT);
	DeleteReg32Buffer(&CAM_REG32SET_WHITE_BALANCE_INCANDESCENT);

	DeleteReg32Buffer(&CAM_REG32SET_WDR_ON);
	DeleteReg32Buffer(&CAM_REG32SET_WDR_OFF);

	DeleteReg32Buffer(&CAM_REG32SET_CONTRAST_M_2);
	DeleteReg32Buffer(&CAM_REG32SET_CONTRAST_M_1);
	DeleteReg32Buffer(&CAM_REG32SET_CONTRAST_0);
	DeleteReg32Buffer(&CAM_REG32SET_CONTRAST_P_1);
	DeleteReg32Buffer(&CAM_REG32SET_CONTRAST_P_2);

	DeleteReg32Buffer(&CAM_REG32SET_SATURATION_M_2);
	DeleteReg32Buffer(&CAM_REG32SET_SATURATION_M_1);
	DeleteReg32Buffer(&CAM_REG32SET_SATURATION_0);
	DeleteReg32Buffer(&CAM_REG32SET_SATURATION_P_1);
	DeleteReg32Buffer(&CAM_REG32SET_SATURATION_P_2);

	DeleteReg32Buffer(&CAM_REG32SET_SHARPNESS_M_2);
	DeleteReg32Buffer(&CAM_REG32SET_SHARPNESS_M_1);
	DeleteReg32Buffer(&CAM_REG32SET_SHARPNESS_0);
	DeleteReg32Buffer(&CAM_REG32SET_SHARPNESS_P_1);
	DeleteReg32Buffer(&CAM_REG32SET_SHARPNESS_P_2);		

	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_M_4);
	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_M_3);
	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_M_2);
	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_M_1);
	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_0);
	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_P_1);
	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_P_2);
	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_P_3);
	DeleteReg32Buffer(&CAM_REG32SET_BRIGHTNESS_P_4);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_OFF);
//	DeleteReg32Buffer(&CAM_REG32SET_SCENE_OFF_NONE);
//	DeleteReg32Buffer(&CAM_REG32SET_SCENE_OFF_SPORTS);
//	DeleteReg32Buffer(&CAM_REG32SET_SCENE_OFF_NIGHT);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_PORTRAIT);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_LANDSCAPE);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_SPORTS);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_PARTY);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_BEACH);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_SUNSET);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_DAWN);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_FALL);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_NIGHT);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_BACKLIGHT);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_FIRE);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_TEXT);
	DeleteReg32Buffer(&CAM_REG32SET_SCENE_CANDLE);
	DeleteReg32Buffer(&CAM_REG32SET_METERING_MATRIX);
	DeleteReg32Buffer(&CAM_REG32SET_METERING_SPOT);
	DeleteReg32Buffer(&CAM_REG32SET_METERING_CENTER);
	DeleteReg32Buffer(&CAM_REG32SET_ISO_AUTO);
	DeleteReg32Buffer(&CAM_REG32SET_ISO_50);
	DeleteReg32Buffer(&CAM_REG32SET_ISO_100);
	DeleteReg32Buffer(&CAM_REG32SET_ISO_200);
	DeleteReg32Buffer(&CAM_REG32SET_ISO_400);
	DeleteReg32Buffer(&CAM_REG32SET_RETURN_TO_PREVIEW);
	DeleteReg32Buffer(&CAM_REG32SET_HIGH_SNAPSHOT);
	DeleteReg32Buffer(&CAM_REG32SET_NORMAL_SNAPSHOT);
	DeleteReg32Buffer(&CAM_REG32SET_LOWLIGHT_SNAPSHOT);
	DeleteReg32Buffer(&CAM_REG32SET_NIGHT_SNAPSHOT);
//	DeleteReg32Buffer(&CAM_REG32SET_5_FPS);
//	DeleteReg32Buffer(&CAM_REG32SET_7_FPS);
//	DeleteReg32Buffer(&CAM_REG32SET_10_FPS);
//	DeleteReg32Buffer(&CAM_REG32SET_15_FPS);
	DeleteReg32Buffer(&CAM_REG32SET_30_FPS);
//	DeleteReg32Buffer(&CAM_REG32SET_AUTO15_FPS);
//	DeleteReg32Buffer(&CAM_REG32SET_AUTO30_FPS);
	DeleteReg32Buffer(&CAM_REG32SET_AE_LOCK);
	DeleteReg32Buffer(&CAM_REG32SET_AE_UNLOCK);
	DeleteReg32Buffer(&CAM_REG32SET_AWB_LOCK);
	DeleteReg32Buffer(&CAM_REG32SET_AWB_UNLOCK);
//	DeleteReg32Buffer(&CAM_REG32SET_AF_DO);
//	DeleteReg32Buffer(&CAM_REG32SET_AF_NORMAL_ON);
//	DeleteReg32Buffer(&CAM_REG32SET_AF_MACRO_ON);
//	DeleteReg32Buffer(&CAM_REG32SET_AF_OFF);
	DeleteReg32Buffer(&CAM_REG32SET_DTP_ON);
	DeleteReg32Buffer(&CAM_REG32SET_DTP_OFF);

	DeleteReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_176_144);
	DeleteReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_320_240);
	DeleteReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_352_288);
	DeleteReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_640_480);
	DeleteReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_720_480);
	DeleteReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_800_480);
	DeleteReg32Buffer(&CAM_REG32SET_CAMCORDER_SIZE_1280_720);

	DeleteReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_144_176);
	DeleteReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_176_144);
	DeleteReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_320_240);
	DeleteReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_640_480);
	DeleteReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_720_480);
	DeleteReg32Buffer(&CAM_REG32SET_PREVIEW_SIZE_800_480);

	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_640_480);
	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_800_480);
	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_1280_960);
	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_1600_960);
	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_1600_1200);
	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_2048_1232);
	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_2048_1536);
	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_2560_1536);
	DeleteReg32Buffer(&CAM_REG32SET_CAPTURE_SIZE_2560_1920);

	DeleteReg32Buffer(&CAM_REG32SET_JPEG_QUALITY_SUPERFINE);
	DeleteReg32Buffer(&CAM_REG32SET_JPEG_QUALITY_FINE);
	DeleteReg32Buffer(&CAM_REG32SET_JPEG_QUALITY_NORMAL);

	DeleteReg32Buffer(&CAM_REG32SET_FLASH_INIT);
	DeleteReg32Buffer(&CAM_REG32SET_LOW_CAP_ON);
	DeleteReg32Buffer(&CAM_REG32SET_LOW_CAP_OFF);

	DeleteReg32Buffer(&CAM_REG32SET_NIGHT_CAP_ON);
	DeleteReg32Buffer(&CAM_REG32SET_NIGHT_CAP_OFF);

	DeleteReg32Buffer(&CAM_REG32SET_AF_START);

	DeleteReg32Buffer(&CAM_REG32SET_AF_NORMAL_MODE_1);
	DeleteReg32Buffer(&CAM_REG32SET_AF_NORMAL_MODE_2);
	DeleteReg32Buffer(&CAM_REG32SET_AF_NORMAL_MODE_3);
	DeleteReg32Buffer(&CAM_REG32SET_AF_NORMAL_MODE_4);

	DeleteReg32Buffer(&CAM_REG32SET_AF_MACRO_MODE_1);
	DeleteReg32Buffer(&CAM_REG32SET_AF_MACRO_MODE_2);
	DeleteReg32Buffer(&CAM_REG32SET_AF_MACRO_MODE_3);

	DeleteReg32Buffer(&CAM_REG32SET_AF_OFF_1);
	DeleteReg32Buffer(&CAM_REG32SET_AF_OFF_2);
	DeleteReg32Buffer(&CAM_REG32SET_AF_OFF_3);

	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_0);
	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_1);
	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_2);
	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_3);
	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_4);
	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_5);
	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_6);
	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_7);
	DeleteReg32Buffer(&CAM_REG32SET_X1_25_ZOOM_8);

	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_0);
	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_1);
	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_2);
	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_3);
	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_4);
	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_5);
	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_6);
	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_7);
	DeleteReg32Buffer(&CAM_REG32SET_X1_6_ZOOM_8);

	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_0);
	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_1);
	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_2);
	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_3);
	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_4);
	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_5);
	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_6);
	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_7);
	DeleteReg32Buffer(&CAM_REG32SET_X1_77_ZOOM_8);

	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_0);
	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_1);
	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_2);
	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_3);
	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_4);
	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_5);
	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_6);
	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_7);
	DeleteReg32Buffer(&CAM_REG32SET_X2_ZOOM_8);
}

