#
# Samsung thermal specific Makefile
#
obj-$(CONFIG_EXYNOS_THERMAL)			+= exynos_thermal.o
exynos_thermal-y				:= exynos_tmu.o
exynos_thermal-y				+= exynos_tmu_data.o
exynos_thermal-y				+= exynos_thermal_common.o
