/*
 * Video for Linux Two header file for samsung
 *
 * Copyright (C) 2009, Dongsoo Nathaniel Kim<dongsoo45.kim@samsung.com>
 *
 * This header file contains several v4l2 APIs to be proposed to v4l2
 * community and until bein accepted, will be used restrictly in Samsung's
 * camera interface driver FIMC.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#ifndef __LINUX_VIDEODEV2_EXYNOS_CAMERA_H
#define __LINUX_VIDEODEV2_EXYNOS_CAMERA_H

/* Following CIDs are menu type */
#define V4L2_CID_SCENEMODE	(V4L2_CID_CAMERA_CLASS_BASE+23)
#define V4L2_CID_CAM_STABILIZE	(V4L2_CID_CAMERA_CLASS_BASE+24)
#define V4L2_CID_CAM_MULTISHOT	(V4L2_CID_CAMERA_CLASS_BASE+25)

/* Control dynamic range */
#define V4L2_CID_CAM_DR		(V4L2_CID_CAMERA_CLASS_BASE+26)

/* White balance preset control */
#define V4L2_CID_WHITE_BALANCE_PRESET	(V4L2_CID_CAMERA_CLASS_BASE+27)
#define V4L2_CID_CAM_SENSOR_FW_VER	(V4L2_CID_CAMERA_CLASS_BASE + 28)
#define V4L2_CID_CAM_PHONE_FW_VER	(V4L2_CID_CAMERA_CLASS_BASE + 29)

#define V4L2_CID_FIMC_IS_BASE		(V4L2_CTRL_CLASS_CAMERA | 0x1000)
#define V4L2_CID_FIMC_IS_TUNE_BASE	(V4L2_CTRL_CLASS_CAMERA | 0x2000)
#define V4L2_CID_SENSOR_BASE		(V4L2_CTRL_CLASS_CAMERA | 0x3000)

#define V4L2_CID_IS_S_STREAM			(V4L2_CID_FIMC_IS_BASE + 14)
enum is_set_stream {
	IS_DISABLE_STREAM,
	IS_ENABLE_STREAM
};

#define V4L2_CID_IS_G_STREAM			(V4L2_CID_FIMC_IS_BASE + 15)
#define V4L2_CID_IS_G_CAPABILITY		(V4L2_CID_FIMC_IS_BASE + 17)
#define V4L2_CID_IS_G_COMPLETES			(V4L2_CID_FIMC_IS_BASE + 18)
#define V4L2_CID_IS_BDS_WIDTH			(V4L2_CID_FIMC_IS_BASE + 19)
#define V4L2_CID_IS_BDS_HEIGHT			(V4L2_CID_FIMC_IS_BASE + 20)
#define V4L2_CID_IS_DVFS_LOCK			(V4L2_CID_FIMC_IS_BASE + 21)
#define V4L2_CID_IS_DVFS_UNLOCK			(V4L2_CID_FIMC_IS_BASE + 22)
#define V4L2_CID_IS_FORCE_DONE			(V4L2_CID_FIMC_IS_BASE + 50)
#define V4L2_CID_IS_SET_SETFILE			(V4L2_CID_FIMC_IS_BASE + 51)
#define V4L2_CID_IS_S_BNS				(V4L2_CID_FIMC_IS_BASE + 52)
#define V4L2_CID_IS_G_BNS_SIZE			(V4L2_CID_FIMC_IS_BASE + 53)
#define V4L2_CID_IS_COLOR_RANGE			(V4L2_CID_FIMC_IS_BASE + 54)
#define V4L2_CID_IS_MIN_TARGET_FPS		(V4L2_CID_FIMC_IS_BASE + 55)
#define V4L2_CID_IS_MAX_TARGET_FPS		(V4L2_CID_FIMC_IS_BASE + 56)
#define V4L2_CID_IS_G_DTPSTATUS			(V4L2_CID_FIMC_IS_BASE + 57)
#define V4L2_CID_IS_END_OF_STREAM		(V4L2_CID_FIMC_IS_BASE + 58)
#define V4L2_CID_IS_MAP_BUFFER			(V4L2_CID_FIMC_IS_BASE + 59)
#define V4L2_CID_IS_INTENT			(V4L2_CID_FIMC_IS_BASE + 60)
#define V4L2_CID_IS_DEBUG_DUMP			(V4L2_CID_FIMC_IS_BASE + 900)
#define V4L2_CID_IS_DEBUG_SYNC_LOG		(V4L2_CID_FIMC_IS_BASE + 901)

#define V4L2_CID_SENSOR_SET_AE_TARGET			(V4L2_CID_SENSOR_BASE + 1)
#define V4L2_CID_SENSOR_SET_AE_WEIGHT_1x1_2		(V4L2_CID_SENSOR_BASE + 2)
#define V4L2_CID_SENSOR_SET_AE_WEIGHT_1x3_4		(V4L2_CID_SENSOR_BASE + 3)
#define V4L2_CID_SENSOR_SET_AE_WEIGHT_2x1_2		(V4L2_CID_SENSOR_BASE + 4)
#define V4L2_CID_SENSOR_SET_AE_WEIGHT_2x3_4		(V4L2_CID_SENSOR_BASE + 5)
#define V4L2_CID_SENSOR_SET_AE_WEIGHT_3x1_2		(V4L2_CID_SENSOR_BASE + 6)
#define V4L2_CID_SENSOR_SET_AE_WEIGHT_3x3_4		(V4L2_CID_SENSOR_BASE + 7)
#define V4L2_CID_SENSOR_SET_AE_WEIGHT_4x1_2		(V4L2_CID_SENSOR_BASE + 8)
#define V4L2_CID_SENSOR_SET_AE_WEIGHT_4x3_4		(V4L2_CID_SENSOR_BASE + 9)
#define V4L2_CID_SENSOR_SET_RG_WEIGHT			(V4L2_CID_SENSOR_BASE + 10)
#define V4L2_CID_SENSOR_SET_AE_SPEED			(V4L2_CID_SENSOR_BASE + 11)
#define V4L2_CID_SENSOR_SET_SHUTTER			(V4L2_CID_SENSOR_BASE + 12)
#define V4L2_CID_SENSOR_SET_GAIN			(V4L2_CID_SENSOR_BASE + 13)
#define V4L2_CID_SENSOR_SET_BIT_CONVERTING		(V4L2_CID_SENSOR_BASE + 14)
#define V4L2_CID_SENSOR_SET_AUTO_EXPOSURE		(V4L2_CID_SENSOR_BASE + 15)
#define V4L2_CID_SENSOR_SET_FRAME_RATE			(V4L2_CID_SENSOR_BASE + 16)

#define V4L2_CID_CAMERA_OIS_SINE_MODE	(V4L2_CID_PRIVATE_BASE+152)

#endif /* __LINUX_VIDEODEV2_EXYNOS_CAMERA_H */
