#!/bin/sh

echo ""
echo "Module ABI/API checker"
echo ""
echo ""

if [ "${#}" != "1"  ]
then
	echo ""
	echo "ERROR: "
	echo "       Usage: ${0} _module_abi_fingerprint_"
	echo ""
	exit 1
fi

kerne_abi_file="/boot/abi/current"

if [ ! -f "${1}" -o ! -f "${kerne_abi_file}" ]
then
	echo ""
	echo "ERROR: Please check \"${1}\", \"${kerne_abi_file}\" files"
	echo ""
	exit 1
fi

ABI_TOOL_LOCATION="/usr/local/bin"
ABI_TOOL_NAME="abi-checker"
ABI_TOOL="${ABI_TOOL_LOCATION}/${ABI_TOOL_NAME}"

if [ -x "${ABI_TOOL}" ]
then
	CMD="${ABI_TOOL}"
elif [ -x "./${ABI_TOOL_NAME}" ]
then
	CMD="./${ABI_TOOL_NAME}"
else
	CMD="${ABI_TOOL_NAME}"
fi

"${CMD}" "test-module" "${kerne_abi_file}" "${1}"

exit ${?}
