obj-$(CONFIG_VIDEO_SAMSUNG_S5P_HDMI_CEC) += s5p-cec.o
s5p-cec-y += cec_drv.o cec_hw.o

obj-$(CONFIG_ODROID_U2_FAN)		+= odroidu2_fan.o
obj-$(CONFIG_ODROID_IOBOARD)  += ioboard-spi.o ioboard-spi-misc.o
