#
# Makefile for IIO Light sensors
#

obj-$(CONFIG_ADJD_S311)		+= adjd_s311.o
obj-$(CONFIG_SENSORS_LM3533)	+= lm3533-als.o
obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
obj-$(CONFIG_VCNL4000)		+= vcnl4000.o
obj-$(CONFIG_HID_SENSOR_ALS)	+= hid-sensor-als.o
obj-$(CONFIG_GP2AP002A00F)	+= gp2ap002a00f.o
obj-$(CONFIG_CM36651)		+= cm36651.o
