obj-$(CONFIG_EXYNOS_ASV)	+= exynos-asv.o
obj-$(CONFIG_EXYNOS_ASV_ARM)	+= exynos5422-asv.o
obj-$(CONFIG_EXYNOS_ASV_ARM64)	+= exynos5433-asv.o

obj-$(CONFIG_EXYNOS_CHIPID)	+= exynos-chipid.o

obj-$(CONFIG_EXYNOS_PMU)	+= exynos-pmu.o exynos-sysram.o
obj-$(CONFIG_EXYNOS_PMU_ARM_DRIVERS)	+= exynos3250-pmu.o exynos4-pmu.o \
					exynos5250-pmu.o exynos5420-pmu.o
obj-$(CONFIG_EXYNOS_PMU_ARM64_DRIVERS)	+= exynos-pm.o exynos5433-pmu.o
obj-$(CONFIG_EXYNOS_PM_DOMAINS) += pm_domains.o
