/*
 * arch/arm/plat-omap/include/mach/mux_latona.h
 *
 */

#ifndef _MUX_LATONA_H_
#define _MUX_LATONA_H_

#define OMAP_GPIO_JACK_NINT			10
#define OMAP_GPIO_FUEL_INT_N		12
#define OMAP_GPIO_NAND_INT			13
#define OMAP_GPIO_GYRO_I2C_SCL		14
#define OMAP_GPIO_GYRO_I2C_SDA		14
#define OMAP_GPIO_CHG_ING_N			16
#define OMAP_GPIO_WLAN_HOST_WAKE	21
#define OMAP_GPIO_SYS_DRM_MSECURE	22	//output
#define OMAP_GPIO_T_FLASH_DETECT	23
#define OMAP_GPIO_KEY_PWRON			24
#define OMAP_GPIO_PS_HOLD_PU		25	//output H
#define OMAP_GPIO_EAR_SEND_END		26
#define OMAP_GPIO_DET_3_5			27
#define OMAP_GPIO_BT_EN				28
#define OMAP_GPIO_TA_NCONNECTED		29
#define OMAP_GPIO_GPS_EN			35
#define OMAP_GPIO_GPS_CNTL			36
#define OMAP_GPIO_SENSOR_SCL		37
#define OMAP_GPIO_SENSOR_SDA		38
#define OMAP_GPIO_GPS_NRST			39
#define OMAP_GPIO_AP_I2C_SCL		40
#define OMAP_GPIO_AP_I2C_SDA		41
#define OMAP_GPIO_CP_RST			43
#define OMAP_GPIO_PCM_SEL			52
#define OMAP_GPIO_PS_VOUT			53
#define OMAP_GPIO_JIG_ON18			54
#define OMAP_GPIO_VIBTONE_FREQ		56
#define OMAP_GPIO_EN_TEMP_VDD		58
#define OMAP_GPIO_BT_NRST			63
#define OMAP_GPIO_CAM_CIF_NRST		64
#define OMAP_GPIO_KEY_HOME			65
#define OMAP_GPIO_5M_CAM_NRST		98
#define OMAP_GPIO_GYRO_INT1			99
#define OMAP_GPIO_GYRO_INT2			100
#define OMAP_GPIO_CAM_CIF_NSTBY		101
#define OMAP_GPIO_EAR_MICBIAS_EN	102
#define OMAP_GPIO_PDA_ACTIVE		111
#define OMAP_GPIO_MSENSE_INT		114
#define OMAP_GPIO_ACC_INT			115
#define OMAP_GPIO_UART_SEL			126
#define OMAP_GPIO_HW_REV1			127
#define OMAP_GPIO_FUEL_SDA			136
#define OMAP_GPIO_FUEL_SCL			137
#define OMAP_GPIO_CAM_FLASH_SET		138
#define OMAP_GPIO_CAM_FLASH_EN		139
#define OMAP_GPIO_RESET_REQ_N		140
#define OMAP_GPIO_VIBTONE_EN		141
#define OMAP_GPIO_TOUCH_INT			142
#define OMAP_GPIO_TOUCH_EN			143
#define OMAP_GPIO_CAM_EN1			152
#define OMAP_GPIO_CAM_5M_NSTBY		153
#define OMAP_GPIO_PHONE_ACTIVE		154
#define OMAP_GPIO_AMP_SHDN			155
#define OMAP_GPIO_BT_HOST_WAKE		156
#define OMAP_GPIO_CHG_EN			157
#define OMAP_GPIO_LED_DRIVER_RST	158
#define OMAP_GPIO_MASSMEMORY_EN		159
#define OMAP_GPIO_WLAN_EN			160
#define OMAP_GPIO_CP_VBUS_EN		161
#define OMAP_GPIO_BT_WAKE			162
#define OMAP_GPIO_HW_REV0			163
#define OMAP_GPIO_MSENSE_NRST		164
#define OMAP_GPIO_MLCD_RST			170
#define OMAP_GPIO_CAM_EN2			186

#endif



