/*
 * Copyright (c) 2018 Samsung Electronics Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * Common Clock Framework support for Exynos9110 SoC.
 */

#include <linux/clk.h>
#include <linux/clkdev.h>
#include <linux/clk-provider.h>
#include <linux/of.h>
#include <linux/of_address.h>
#include <soc/samsung/cal-if.h>
#include <dt-bindings/clock/exynos9110.h>

#include "../../soc/samsung/cal-if/exynos9110/cmucal-vclk.h"
#include "../../soc/samsung/cal-if/exynos9110/cmucal-node.h"
#include "../../soc/samsung/cal-if/exynos9110/cmucal-qch.h"
#include "../../soc/samsung/cal-if/exynos9110/clkout_exynos9110.h"

#include "composite.h"

static struct samsung_clk_provider *exynos9110_clk_provider;
/*
 * list of controller registers to be saved and restored during a
 * suspend/resume cycle.
 */
/* fixed rate clocks generated outside the soc */
struct samsung_fixed_rate exynos9110_fixed_rate_ext_clks[] __initdata = {
	FRATE(OSCCLK, "fin_pll", NULL, 0, 26000000),
};

/* HWACG VCLK */
struct init_vclk exynos9110_apm_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_APM_BUS, MUX_CLKCMU_APM_BUS_USER, "UMUX_CLKCMU_APM_BUS", NULL, 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_APM_CMU_APM, APM_CMU_APM_QCH, "GATE_APM_CMU_APM", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DTZPC_APM, DTZPC_APM_QCH, "GATE_DTZPC_APM", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_APM_AP, MAILBOX_APM_AP_QCH, "GATE_MAILBOX_APM_AP", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_APM_CHUB, MAILBOX_APM_CHUB_QCH, "GATE_MAILBOX_APM_CHUB_", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_APM_CP, MAILBOX_APM_CP_QCH, "GATE_MAILBOX_APM_CP_", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_APM_GNSS, MAILBOX_APM_GNSS_QCH, "GATE_MAILBOX_APM_GNSS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_APM_VTS, MAILBOX_APM_VTS_QCH, "GATE_MAILBOX_APM_VTS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_APM_WLBT, MAILBOX_APM_WLBT_QCH, "GATE_MAILBOX_APM_WLBT", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SPEEDY_APM, SPEEDY_APM_QCH, "GATE_SPEEDY_APM", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_APM, WDT_APM_QCH, "GATE_WDT_APM", "UMUX_CLKCMU_AP_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_cmgp_hwacg_vclks[] __initdata = {
	HWACG_VCLK(DOUT_CLK_CMGP_BUS, DIV_CLK_APM_BUS, "DOUT_CLK_CMGP_BUS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CMGP_I2C0, MUX_CLK_CMGP_I2C0, "UMUX_CLK_CMGP_I2C0", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CMGP_USI0, MUX_CLK_CMGP_USI0, "UMUX_CLK_CMGP_USI0", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CMGP_USI1, MUX_CLK_CMGP_USI1, "UMUX_CLK_CMGP_USI1", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CMGP_USI2, MUX_CLK_CMGP_USI2, "UMUX_CLK_CMGP_USI2", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CMGP_USI3, MUX_CLK_CMGP_USI3, "UMUX_CLK_CMGP_USI3", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CMGP_I2C1, MUX_CLK_CMGP_I2C1, "UMUX_CLK_CMGP_I2C1", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CMGP_I2C2, MUX_CLK_CMGP_I2C2, "UMUX_CLK_CMGP_I2C2", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CMGP_I2C3, MUX_CLK_CMGP_I2C3, "UMUX_CLK_CMGP_I2C3", NULL, 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_ADC_CMGP_S0, ADC_CMGP_QCH_S0, "GATE_ADC_CMGP_S0", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ADC_CMGP_S1, ADC_CMGP_QCH_S1, "GATE_ADC_CMGP_S1", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ADC_CMGP_ADC, ADC_CMGP_QCH_ADC, "GATE_ADC_CMGP_ADC", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CMGP_CMU_CMGP, CMGP_CMU_CMGP_QCH, "GATE_CMGP_CMU_CMGP", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DTZPC_CMGP, DTZPC_CMGP_QCH, "GATE_DTZPC_CMGP", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_GPIO_CMGP, GPIO_CMGP_QCH, "GATE_GPIO_CMGP", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP0, I2C_CMGP0_QCH, "GATE_I2C_CMGP0", "UMUX_CLK_CMGP_I2C0", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP1, I2C_CMGP1_QCH, "GATE_I2C_CMGP1", "UMUX_CLK_CMGP_I2C1", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP2, I2C_CMGP2_QCH, "GATE_I2C_CMGP2", "UMUX_CLK_CMGP_I2C2", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP3, I2C_CMGP3_QCH, "GATE_I2C_CMGP3", "UMUX_CLK_CMGP_I2C3", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP4, I2C_CMGP4_QCH, "GATE_I2C_CMGP4", "DOUT_CLK_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP5, I2C_CMGP5_QCH, "GATE_I2C_CMGP5", "DOUT_CLK_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP6, I2C_CMGP6_QCH, "GATE_I2C_CMGP6", "DOUT_CLK_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_CMGP0, USI_CMGP0_QCH, "GATE_USI_CMGP0", "UMUX_CLK_CMGP_USI0", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_CMGP1, USI_CMGP1_QCH, "GATE_USI_CMGP1", "UMUX_CLK_CMGP_USI1", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_CMGP2, USI_CMGP2_QCH, "GATE_USI_CMGP2", "UMUX_CLK_CMGP_USI2", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_CMGP3, USI_CMGP3_QCH, "GATE_USI_CMGP3", "UMUX_CLK_CMGP_USI3", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_chub_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLK_CHUB_BUS, MUX_CLK_CHUB_BUS, "UMUX_CLK_CHUB_BUS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CHUB_USI0, MUX_CLK_CHUB_USI0, "UMUX_CLK_CHUB_USI0", "UMUX_CLKCMU_CHUB_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CHUB_I2C0, MUX_CLK_CHUB_I2C0, "UMUX_CLK_CHUB_I2C0", "UMUX_CLKCMU_CHUB_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLK_CHUB_I2C1, MUX_CLK_CHUB_I2C1, "UMUX_CLK_CHUB_I2C1", "UMUX_CLKCMU_CHUB_BUS", 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_USI_CHUB00, USI_CHUB00_QCH, "GATE_USI_CHUB00", "UMUX_CLK_CHUB_USI0", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CHUB00, I2C_CHUB00_QCH, "GATE_I2C_CHUB00", "UMUX_CLK_CHUB_I2C0", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CHUB01, I2C_CHUB01_QCH, "GATE_I2C_CHUB01", "UMUX_CLK_CHUB_I2C1", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TIMER_CHUB, TIMER_CHUB_QCH, "GATE_TIMER_CHUB", "UMUX_CLKCMU_CHUB_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_CHUB, WDT_CHUB_QCH, "GATE_WDT_CHUB", "UMUX_CLKCMU_CHUB_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_is_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_IS_BUS, MUX_CLKCMU_IS_BUS_USER, "UMUX_CLKCMU_IS_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_IS_VRA, MUX_CLKCMU_IS_VRA_USER, "UMUX_CLKCMU_IS_VRA", "UMUX_CLKCMU_IS_BUS", 0, 0, NULL),

	HWACG_VCLK(GATE_D_TZPC_IS, D_TZPC_IS_QCH, "GATE_D_TZPC_IS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IS_CMU_IS, IS_CMU_IS_QCH, "GATE_IS_CMU_IS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IS3P21P0_IS_S_ISP_ISP, IS3P21P0_IS_QCH_S_ISP_ISP, "GATE_IS3P21P0_IS_S_ISP_ISP", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IS3P21P0_IS_S_ISP_VRA, IS3P21P0_IS_QCH_S_ISP_VRA, "GATE_IS3P21P0_IS_S_ISP_VRA", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IS3P21P0_IS_S_ISP_SMMU_IS, IS3P21P0_IS_QCH_S_ISP_SMMU_IS, "GATE_IS3P21P0_IS_S_ISP_SMMU_IS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IS3P21P0_IS_S_ISP_MCSC, IS3P21P0_IS_QCH_S_ISP_MCSC, "GATE_IS3P21P0_IS_S_ISP_MCSC", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IS3P21P0_IS_S_ISP_PPMU_IS, IS3P21P0_IS_QCH_S_ISP_PPMU_IS, "GATE_IS3P21P0_IS_S_ISP_PPMU_IS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IS3P21P0_IS_S_ISP_CSIS, IS3P21P0_IS_QCH_S_ISP_CSIS, "GATE_IS3P21P0_IS_S_ISP_CSIS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IS3P21P0_IS_S_ISP_CSIS_DMA, IS3P21P0_IS_QCH_S_ISP_CSIS_DMA, "GATE_IS3P21P0_IS_S_ISP_CSIS_DMA", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_cmu_hwacg_vclks[] __initdata = {
};

struct init_vclk exynos9110_dispaud_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_DISPAUD_DISP, MUX_CLKCMU_DISPAUD_DISP_USER, "UMUX_CLKCMU_DISPAUD_DISP", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_ABOX_CPU, ABOX_QCH_CPU, "GATE_ABOX_CPU", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_S_ACLK, ABOX_QCH_S_ACLK, "GATE_ABOX_S_ACLK", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_S_BCLK0, ABOX_QCH_S_BCLK0, "GATE_ABOX_S_BCLK0", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_S_BCLK1, ABOX_QCH_S_BCLK1, "GATE_ABOX_S_BCLK1", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_S_BCLK2, ABOX_QCH_S_BCLK2, "GATE_ABOX_S_BCLK2", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_FM, ABOX_QCH_FM, "GATE_ABOX_FM", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_S_IRQ, ABOX_QCH_S_IRQ, "GATE_ABOX_S_IRQ", NULL, 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_DISPAUD_CMU_DISPAUD, DISPAUD_CMU_DISPAUD_QCH, "GATE_DISPAUD_CMU_DISPAUD", "UMUX_CLKCMU_DISPAUD_DISP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DPU_S_DPP, DPU_QCH_S_DPP, "GATE_DPU_S_DPP", "UMUX_CLKCMU_DISPAUD_DISP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DPU_S_DMA, DPU_QCH_S_DMA, "GATE_DPU_S_DMA", "UMUX_CLKCMU_DISPAUD_DISP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DPU_S_DECON, DPU_QCH_S_DECON, "GATE_DPU_S_DECON", "UMUX_CLKCMU_DISPAUD_DISP", 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_SMMU_ABOX, SMMU_ABOX_QCH, "GATE_SMMU_ABOX", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SMMU_DPU, SMMU_DPU_QCH, "GATE_SMMU_DPU", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_AUD, WDT_AUD_QCH, "GATE_WDT_AUD", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_ABOX_VTS, MAILBOX_ABOX_VTS_QCH, "GATE_MAILBOX_ABOX_VTS", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_fsys_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_FSYS_BUS, MUX_CLKCMU_FSYS_BUS_USER, "UMUX_CLKCMU_FSYS_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_FSYS_MMC_CARD, MUX_CLKCMU_FSYS_MMC_CARD_USER, "UMUX_CLKCMU_FSYS_MMC_CARD", "UMUX_CLKCMU_FSYS_BUS", 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_FSYS_MMC_EMBD, MUX_CLKCMU_FSYS_MMC_EMBD_USER, "UMUX_CLKCMU_FSYS_MMC_EMBD", "UMUX_CLKCMU_FSYS_BUS", 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_FSYS_USB20DRD, MUX_CLKCMU_FSYS_USB20DRD_USER, "UMUX_CLKCMU_FSYS_USB20DRD", "UMUX_CLKCMU_FSYS_BUS", 0, 0, NULL),

	HWACG_VCLK(GATE_MMC_CARD, MMC_CARD_QCH, "GATE_MMC_CARD", "UMUX_CLKCMU_FSYS_MMC_CARD", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MMC_EMBD, MMC_EMBD_QCH, "GATE_MMC_EMBD", "UMUX_CLKCMU_FSYS_MMC_EMBD", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USB20DRD_TOP_LINK, USB20DRD_TOP_QCH_LINK, "GATE_USB20DRD_TOP_LINK", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USB20DRD_TOP_20CTRL, USB20DRD_TOP_QCH_20CTRL, "GATE_USB20DRD_TOP_20CTRL", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USB20DRD_TOP_REFCLK, USB20DRD_TOP_QCH_REFCLK, "GATE_USB20DRD_TOP_REFCLK", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_g3d_hwacg_vclks[] __initdata = {
	HWACG_VCLK(GATE_D_TZPC_G3D, D_TZPC_G3D_QCH, "GATE_D_TZPC_G3D", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_G3D, G3D_QCH, "GATE_G3D", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_G3D_CMU_G3D, G3D_CMU_G3D_QCH, "GATE_G3D_CMU_G3D", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_mfcmscl_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_MFCMSCL_MFC, MUX_CLKCMU_MFCMSCL_MFC_USER, "UMUX_CLKCMU_MFCMSCL_MFC", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_MFCMSCL_MSCL, MUX_CLKCMU_MFCMSCL_MSCL_USER, "UMUX_CLKCMU_MFCMSCL_MSCL", "UMUX_CLKCMU_MFCMSCL_MFC", 0, 0, NULL),

	HWACG_VCLK(GATE_D_TZPC_MFCMSCL, D_TZPC_MFCMSCL_QCH, "GATE_D_TZPC_MFCMSCL", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_JPEG, JPEG_QCH, "GATE_JPEG", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_M2M, M2M_QCH, "GATE_M2M", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MCSC, MCSC_QCH, "GATE_MCSC", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MFC, MFC_QCH, "GATE_MFC", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MFCMSCL_CMU_MFCMSCL, MFCMSCL_CMU_MFCMSCL_QCH, "GATE_MFCMSCL_CMU_MFCMSCL", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PPMU_MFCMSCL, PPMU_MFCMSCL_QCH, "GATE_PPMU_MFCMSCL", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_MFCMSCL, SYSMMU_MFCMSCL_QCH, "GATE_SYSMMU_MFCMSCL", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_mif_hwacg_vclks[] __initdata = {
	HWACG_VCLK(GATE_CMU_MIF_CMUREF, CMU_MIF_CMUREF_QCH, "GATE_CMU_MIF_CMUREF", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMC, DMC_QCH, "GATE_DMC", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_D_TZPC_MIF, D_TZPC_MIF_QCH, "GATE_D_TZPC_MIF", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MIF_CMU_MIF, MIF_CMU_MIF_QCH, "GATE_MIF_CMU_MIF", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PPMU_DMC_CPU, PPMU_DMC_CPU_QCH, "GATE_PPMU_DMC_CPU", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_QE_DMC_CPU, QE_DMC_CPU_QCH, "GATE_QE_DMC_CPU", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_MIF, SYSREG_MIF_QCH, "GATE_SYSREG_MIF", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_core_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_CORE_BUS, MUX_CLKCMU_CORE_BUS_USER, "UMUX_CLKCMU_CORE_BUS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PDMA_CORE, PDMA_CORE_QCH, "GATE_PDMA_CORE", "UMUX_CLKCMU_CORE_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_peri_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_PERI_BUS, MUX_CLKCMU_PERI_BUS_USER, "UMUX_CLKCMU_PERI_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_PERI_IP, MUX_CLKCMU_PERI_IP_USER, "UMUX_CLKCMU_PERI_IP", "UMUX_CLKCMU_PERI_BUS", 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_PERI_UART, MUX_CLKCMU_PERI_UART_USER, "UMUX_CLKCMU_PERI_UART", "UMUX_CLKCMU_PERI_BUS", 0, 0, NULL),

	HWACG_VCLK(GATE_I2C_0, I2C_0_QCH, "GATE_I2C_0", "UMUX_CLKCMU_PERI_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_1, I2C_1_QCH, "GATE_I2C_1", "UMUX_CLKCMU_PERI_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_2, I2C_2_QCH, "GATE_I2C_2", "UMUX_CLKCMU_PERI_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MCT, MCT_QCH, "GATE_MCT", "UMUX_CLKCMU_PERI_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_OTP_CON_TOP, OTP_CON_TOP_QCH, "GATE_OTP_CON_TOP", "UMUX_CLKCMU_PERI_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERI_CMU_PERI, PERI_CMU_PERI_QCH, "GATE_PERI_CMU_PERI", "UMUX_CLKCMU_PERI_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PWM_MOTOR, PWM_MOTOR_QCH, "GATE_PWM_MOTOR", "UMUX_CLKCMU_PERI_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI00_I2C, USI00_I2C_QCH, "GATE_USI00_I2C", "UMUX_CLKCMU_PERI_IP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI00_USI, USI00_USI_QCH, "GATE_USI00_USI", "UMUX_CLKCMU_PERI_IP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_I2C_0, USI_I2C_0_QCH, "GATE_USI_I2C_0", "UMUX_CLKCMU_PERI_IP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_SPI, USI_SPI_QCH, "GATE_USI_SPI", "UMUX_CLKCMU_PERI_IP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_UART, USI_UART_QCH, "GATE_USI_UART", "UMUX_CLKCMU_PERI_IP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_CLUSTER0, WDT_CLUSTER0_QCH, "GATE_WDT_CLUSTER0", "UMUX_CLKCMU_PERI_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9110_vts_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_VTS_BUS, MUX_CLK_RCO_VTS_USER, "UMUX_CLKCMU_VTS_BUS", NULL, 0, VCLK_NOINIT, NULL),

	HWACG_VCLK(GATE_VTS_CPU, CORTEXM4INTEGRATION_QCH, "GATE_CORTEXM4_CPU", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE | VCLK_NOINIT, NULL),
	HWACG_VCLK(GATE_VTS_DMIC_IF, DMIC_IF_QCH_DMIC_CLK, "GATE_DMIC_IF", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE | VCLK_NOINIT, NULL),
	HWACG_VCLK(GATE_HWACG_SYS_DMIC0, HWACG_SYS_DMIC0_QCH, "GATE_HWACG_SYS_DMIC0", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE | VCLK_NOINIT, NULL),
	HWACG_VCLK(GATE_HWACG_SYS_DMIC1, HWACG_SYS_DMIC1_QCH, "GATE_HWACG_SYS_DMIC1", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE | VCLK_NOINIT, NULL),
	HWACG_VCLK(GATE_WDT_VTS, WDT_VTS_QCH, "GATE_WDT_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE | VCLK_NOINIT, NULL),
	HWACG_VCLK(GATE_U_DMIC_CLK_MUX, U_DMIC_CLK_MUX_QCH, "GATE_U_DMIC_CLK_MUX", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE | VCLK_NOINIT, NULL),
};

/* Special VCLK */
struct init_vclk exynos9110_apm_vclks[] __initdata = {
	VCLK(APM_BUS, DIV_CLK_APM_BUS, "APM_BUS", 0, 0, NULL),
};

struct init_vclk exynos9110_cmgp_vclks[] __initdata = {
	VCLK(CMGP_BUS, CLKCMU_CMGP_BUS, "CMGP_BUS", 0, 0, NULL),
	VCLK(CMGP_ADC, DIV_CLK_CMGP_ADC, "CMGP_ADC", 0, 0, NULL),
	VCLK(CMGP_I2C0, DIV_CLK_CMGP_I2C0, "CMGP_I2C0", 0, 0, NULL),
	VCLK(CMGP_USI0, DIV_CLK_CMGP_USI0, "CMGP_USI0", 0, 0, NULL),
	VCLK(CMGP_USI1, DIV_CLK_CMGP_USI1, "CMGP_USI1", 0, 0, NULL),
	VCLK(CMGP_USI2, DIV_CLK_CMGP_USI2, "CMGP_USI2", 0, 0, NULL),
	VCLK(CMGP_USI3, DIV_CLK_CMGP_USI3, "CMGP_USI3", 0, 0, NULL),
	VCLK(CMGP_I2C1, DIV_CLK_CMGP_I2C1, "CMGP_I2C1", 0, 0, NULL),
	VCLK(CMGP_I2C2, DIV_CLK_CMGP_I2C2, "CMGP_I2C2", 0, 0, NULL),
	VCLK(CMGP_I2C3, DIV_CLK_CMGP_I2C3, "CMGP_I2C3", 0, 0, NULL),
};

struct init_vclk exynos9110_chub_vclks[] __initdata = {
	VCLK(CHUB_BUS, DIV_CLK_CHUB_BUS, "CHUB_BUS", 0, 0, NULL),
	VCLK(CHUB_USI0, DIV_CLK_CHUB_USI0, "CHUB_USI0", 0, 0, NULL),
	VCLK(CHUB_I2C0, DIV_CLK_CHUB_I2C0, "CHUB_I2C0", 0, 0, NULL),
	VCLK(CHUB_I2C1, DIV_CLK_CHUB_I2C1, "CHUB_I2C1", 0, 0, NULL),
};

struct init_vclk exynos9110_is_vclks[] __initdata = {
	VCLK(CIS_CLK0, CLKCMU_CIS_CLK0, "CIS_CLK0", 0, 0, NULL),
	VCLK(CIS_CLK1, CLKCMU_CIS_CLK1, "CIS_CLK1", 0, 0, NULL),
	VCLK(IS_BUS, CLKCMU_IS_BUS, "IS_BUS", 0, 0, NULL),
	VCLK(IS_VRA, CLKCMU_IS_VRA, "IS_VRA", 0, 0, NULL),
};

struct init_vclk exynos9110_fsys_vclks[] __initdata = {
	VCLK(FSYS_BUS, CLKCMU_FSYS_BUS, "FSYS_BUS", 0, 0, NULL),
	VCLK(FSYS_MMC_EMBD, CLKCMU_FSYS_MMC_EMBD, "FSYS_MMC_EMBD", 0, 0, NULL),
	VCLK(FSYS_USB20DRD, CLKCMU_FSYS_USB20DRD, "FSYS_USB20DRD", 0, 0, NULL),
	VCLK(FSYS_MMC_CARD, CLKCMU_FSYS_MMC_CARD, "FSYS_MMC_CARD", 0, 0, NULL),
};

struct init_vclk exynos9110_peri_vclks[] __initdata = {
	VCLK(PERI_BUS, CLKCMU_PERI_BUS, "PERI_BUS", 0, 0, NULL),
	VCLK(PERI_UART, CLKCMU_PERI_UART, "PERI_UART", 0, 0, NULL),
	VCLK(PERI_HSI2C, DIV_CLK_PERI_HSI2C, "PERI_HSI2C", 0, 0, NULL),
	VCLK(PERI_SPI, DIV_CLK_PERI_SPI, "PERI_SPI", 0, 0, NULL),
	VCLK(PERI_USI00_I2C, DIV_CLK_PERI_USI00_I2C, "PERI_USI00_I2C", 0, 0, NULL),
	VCLK(PERI_USI00_USI, DIV_CLK_PERI_USI00_USI, "PERI_USI00_USI", 0, 0, NULL),
};

struct init_vclk exynos9110_dispaud_vclks[] __initdata = {
	VCLK(DISPAUD_DISP, CLKCMU_DISPAUD_DISP, "DISPAUD_DISP", 0, 0, NULL),
	VCLK(PLL_OUT_AUD, PLL_AUD, "PLL_OUT_AUD", 0, 0, NULL),
	VCLK(DOUT_AUD_AUDIF, DIV_CLK_AUD_AUDIF, "DOUT_AUD_AUDIF", 0, 0, NULL),
	VCLK(DOUT_AUD_ACLK, DIV_CLK_AUD_CPU_ACLK, "DOUT_AUD_ACLK", 0, 0, NULL),
	VCLK(DOUT_AUD_UAIF0, DIV_CLK_AUD_UAIF0, "DOUT_AUD_UAIF0", 0, 0, NULL),
	VCLK(DOUT_AUD_UAIF1, DIV_CLK_AUD_UAIF1, "DOUT_AUD_UAIF1", 0, 0, NULL),
};

struct init_vclk exynos9110_vts_vclks[] __initdata = {
	VCLK(CLK_VTS_DMIC_IF, DIV_CLK_VTS_DMIC_IF, "CLK_VTS_DMIC_IF", 0, VCLK_NOINIT, NULL),
	VCLK(CLK_VTS_DMIC, DIV_CLK_VTS_DMIC, "CLK_VTS_DMIC", 0, VCLK_NOINIT, NULL),
	VCLK(CLK_VTS_DMIC_IF_DIV2, DIV_CLK_VTS_DMIC_IF_DIV2, "CLK_VTS_DMIC_IF_DIV2", 0, VCLK_NOINIT, NULL),
};

struct init_vclk exynos9110_g3d_vclks[] __initdata = {
};


struct init_vclk exynos9110_dvfs_vclks[] __initdata = {
};

/* Clock out */
struct init_vclk exynos9110_clkout_vclks[] __initdata = {
	VCLK(OSCCLK_AUD, VCLK_CLKOUT, "OSCCLK_AUD", 0,0, NULL),
};

static __initdata struct of_device_id ext_clk_match[] = {
	{.compatible = "samsung,exynos9110-oscclk", .data = (void *)0},
	{},
};

void exynos9110_vclk_init(void)
{
	/* Common clock init */
}

extern void __init samsung_register_of_fixed_ext(
		struct samsung_clk_provider *ctx,
		struct samsung_fixed_rate *fixed_rate_clk,
		unsigned int nr_fixed_rate_clk,
		struct of_device_id *clk_matches);

extern void __init samsung_register_vclk(struct samsung_clk_provider *ctx,
		struct init_vclk *list, unsigned int nr_vclk);
/* register exynos9110 clocks */
void __init exynos9110_clk_init(struct device_node *np)
{
	void __iomem *reg_base;
	int ret;

	if (np) {
		reg_base = of_iomap(np, 0);
		if (!reg_base)
			panic("%s: failed to map registers\n", __func__);
	} else {
		panic("%s: unable to determine soc\n", __func__);
	}

	ret = cal_if_init(np);
	if (ret)
		panic("%s: unable to initialize cal-if\n", __func__);

	exynos9110_clk_provider = samsung_clk_init(np, reg_base, CLK_NR_CLKS);
	if (!exynos9110_clk_provider)
		panic("%s: unable to allocate context.\n", __func__);

	samsung_register_of_fixed_ext(exynos9110_clk_provider, exynos9110_fixed_rate_ext_clks,
			ARRAY_SIZE(exynos9110_fixed_rate_ext_clks),
			ext_clk_match);
	/* register HWACG vclk */
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_apm_hwacg_vclks, ARRAY_SIZE(exynos9110_apm_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_cmgp_hwacg_vclks, ARRAY_SIZE(exynos9110_cmgp_hwacg_vclks));
//	samsung_register_vclk(exynos9110_clk_provider, exynos9110_chub_hwacg_vclks, ARRAY_SIZE(exynos9110_chub_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_vts_hwacg_vclks, ARRAY_SIZE(exynos9110_vts_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_is_hwacg_vclks, ARRAY_SIZE(exynos9110_is_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_cmu_hwacg_vclks, ARRAY_SIZE(exynos9110_cmu_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_dispaud_hwacg_vclks, ARRAY_SIZE(exynos9110_dispaud_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_fsys_hwacg_vclks, ARRAY_SIZE(exynos9110_fsys_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_g3d_hwacg_vclks, ARRAY_SIZE(exynos9110_g3d_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_mfcmscl_hwacg_vclks, ARRAY_SIZE(exynos9110_mfcmscl_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_mif_hwacg_vclks, ARRAY_SIZE(exynos9110_mif_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_core_hwacg_vclks, ARRAY_SIZE(exynos9110_core_hwacg_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_peri_hwacg_vclks, ARRAY_SIZE(exynos9110_peri_hwacg_vclks));

	/* register special vclk */
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_apm_vclks, ARRAY_SIZE(exynos9110_apm_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_cmgp_vclks, ARRAY_SIZE(exynos9110_cmgp_vclks));
//	samsung_register_vclk(exynos9110_clk_provider, exynos9110_chub_vclks, ARRAY_SIZE(exynos9110_chub_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_is_vclks, ARRAY_SIZE(exynos9110_is_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_fsys_vclks, ARRAY_SIZE(exynos9110_fsys_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_peri_vclks, ARRAY_SIZE(exynos9110_peri_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_dispaud_vclks, ARRAY_SIZE(exynos9110_dispaud_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_g3d_vclks, ARRAY_SIZE(exynos9110_g3d_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_dvfs_vclks, ARRAY_SIZE(exynos9110_dvfs_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_clkout_vclks, ARRAY_SIZE(exynos9110_clkout_vclks));
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_vts_vclks, ARRAY_SIZE(exynos9110_vts_vclks));

	/* register DVFS vclk */
	samsung_register_vclk(exynos9110_clk_provider, exynos9110_dvfs_vclks, ARRAY_SIZE(exynos9110_dvfs_vclks));

	clk_register_fixed_factor(NULL, "pwm-clock", "fin_pll",CLK_SET_RATE_PARENT, 1, 1);

	samsung_clk_of_add_provider(np, exynos9110_clk_provider);

	late_time_init = exynos9110_vclk_init;

	pr_info("EXYNOS9110: Clock setup completed\n");
}

CLK_OF_DECLARE(exynos9110_clk, "samsung,exynos9110-clock", exynos9110_clk_init);
