#
# Makefile for the kernel mobicore drivers
#

obj-$(CONFIG_SOC_EXYNOS3470) += gud-exynos3470/
obj-$(CONFIG_SOC_EXYNOS5260) += gud-exynos5260/
obj-$(CONFIG_SOC_EXYNOS5410) += gud-exynos5410/
obj-$(CONFIG_SOC_EXYNOS5420) += gud-exynos5420/
obj-$(CONFIG_SOC_EXYNOS4415) += gud-exynos4415/
obj-$(CONFIG_SOC_EXYNOS3250) += gud-exynos3250/
obj-$(CONFIG_TRUSTONIC_TRUSTED_UI) += TlcTui/
